version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/var/lib/mysql  # Data MySQL
      - ./mysql:/docker-entrypoint-initdb.d  # Pastikan folder ./mysql ada dan berisi init.sql
