version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: mysql10
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-init db.d/init.sql
      - ./docker/mysql/data:/var/lib/mysql